new flow for build sports app

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -3,22 +3,48 @@ run-name: ${{ github.actor }} is compiling our Sample App 🚀
 on: [push]
 jobs:
   compile:
-    name: OpenEdge Compile job
+    name: OpenEdge Compile Job
     runs-on: self-hosted
+    defaults:
+      run:
+        working-directory: ./Sports
     steps:
-      - name: Clean-up
-        run: rm -Rf *
       - uses: actions/checkout@v3
-      - run: sh gradlew clean build
-        working-directory: ./SportsApp
-      - uses: actions/upload-artifact@v2  # upload test results
-        if: success() || failure()        # run this step even if previous step failed
+      - name: Running Gradle build
+        run: sh gradlew clean build
+      - name: Setup Python                # needed by publish step
+        uses: actions/setup-python@v4
         with:
-          name: test-results
-          path: ./SportsApp/Sports/build/test-results/test/results.xml
-      - name: upload zip file to nexus
-        run: curl -v -k -u admin:${{secrets.DOCKER_PWD}} --upload-file ./build/distributions/sportsApp.tar.gz ${{vars.NEXUS_URL}}/com/progess/${{vars.SAMPLEAPP_NAME}}/${{vars.SAMPLEAPP_VERSION}}/${{vars.SAMPLEAPP_NAME}}-${{vars.SAMPLEAPP_VERSION}}.tar.gz
-        working-directory: ./SportsApp
+          python-version: 3.8
+      - name: Publish ABL Unit Test Results
+        uses: EnricoMi/publish-unit-test-result-action/composite@v2
+        with:
+          files: ./build/test-results/**/*.xml
+      # - uses: actions/upload-artifact@v2  # upload test results
+      #   if: success() || failure()        # run this step even if previous step failed
+      #   with:
+      #     name: test-results
+      #     path: ./build/test-results/test/results.xml
+      # - name: upload zip file to nexus
+      #   run: curl -v -k -u admin:${{secrets.DOCKER_PWD}} --upload-file ./build/distributions/sportsApp.tar.gz ${{vars.NEXUS_URL}}/com/progess/${{vars.SAMPLEAPP_NAME}}/${{vars.SAMPLEAPP_VERSION}}/${{vars.SAMPLEAPP_NAME}}-${{vars.SAMPLEAPP_VERSION}}.tar.gz
+      #   working-directory: ./SportsApp
+  build:
+    name: Build Docker Image for Sports App
+    needs: compile
+    defaults:
+      run:
+        working-directory: ./Sports/docker
+    steps:
+      - name: Copy ABLApp archive ('.oear')
+        run: cp -rf ./../build/distributions/ablapps/*.oear ./ablapps
+      - name: Docker build
+        run: sh build.sh
+      - name: Test Docker Image state - Goss
+        run: sh test.sh
+      - name: Publish Goss Test Results
+        uses: EnricoMi/publish-unit-test-result-action/composite@v2
+        with:
+          files: ./unitTestReport.xml
   deploy:
     name: Sample App Deploy
     needs: compile
@@ -53,31 +79,31 @@ jobs:
         uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file: 'trivy-results.sarif'
-  report:
-    name: Publish Reports 
-    permissions: write-all
-    needs: compile
-    if: always()
-    runs-on: self-hosted
-    steps:
-    - name: Retrieve saved test report
-      uses: actions/download-artifact@v2
-      with:
-        name: test-results
-        path: test-results/test
-    # - uses: dorny/test-reporter@v1.6.0
-    #   with:
-    #     name: ABL Unit Test Results           # Name of the check run which will be created
-    #     path: test-results/test/results.xml   # Path to test results
-    #     reporter: java-junit                  # Format of test results
-    - name: Setup Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: 3.8
-    - name: Publish Test Results
-      uses: EnricoMi/publish-unit-test-result-action/composite@v2
-      with:
-        files: test-results/**/*.xml
+  # report:
+  #   name: Publish Reports 
+  #   permissions: write-all
+  #   needs: compile
+  #   if: always()
+  #   runs-on: self-hosted
+  #   steps:
+  #   - name: Retrieve saved test report
+  #     uses: actions/download-artifact@v2
+  #     with:
+  #       name: test-results
+  #       path: test-results/test
+  #   # - uses: dorny/test-reporter@v1.6.0
+  #   #   with:
+  #   #     name: ABL Unit Test Results           # Name of the check run which will be created
+  #   #     path: test-results/test/results.xml   # Path to test results
+  #   #     reporter: java-junit                  # Format of test results
+  #   - name: Setup Python
+  #     uses: actions/setup-python@v4
+  #     with:
+  #       python-version: 3.8
+  #   - name: Publish Test Results
+  #     uses: EnricoMi/publish-unit-test-result-action/composite@v2
+  #     with:
+  #       files: test-results/**/*.xml
 #  test:
 #    name: Test deploy of Sample App
 #    needs: deploy
